#!/usr/bin/env node
/**
 * og-metrics: the link card's measuring table, read out of the font files it
 * renders with.
 *
 *   node scripts/og-metrics.mjs     (rewrites lib/ogMetrics.ts)
 *
 * The per-mechanic link card (app/[slug]/opengraph-image.tsx) sizes the
 * business name, wraps every line itself and decides what fits BEFORE satori
 * draws it, because satori cannot be asked how wide a string is. So the card
 * carries the advance width of every glyph it can draw, taken from the exact
 * WOFF files in assets/fonts, plus the ink box of every signage glyph (how far
 * a Q's tail or an accent reaches past the line), which sets the name's
 * leading. Re-run this whenever a file in assets/fonts changes.
 *
 * Reads WOFF v1 only (zlib tables): cmap format 4/12, hhea, hmtx, head, and
 * loca/glyf for the ink boxes of TrueType-outline faces.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { inflateSync } from 'node:zlib';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const FACES = {
  sign800: 'BigShoulders-800.woff',
  sign700: 'BigShoulders-700.woff',
  text600: 'Geist-600.woff',
  text500: 'Geist-500.woff',
  voice: 'Newsreader-Italic-400.woff',
};
const MAX_CP = 0x2122;

function tables(buf) {
  if (buf.toString('latin1', 0, 4) !== 'wOFF') throw new Error('not a WOFF v1 file');
  const n = buf.readUInt16BE(12);
  const out = {};
  for (let i = 0; i < n; i++) {
    const o = 44 + i * 20;
    const tag = buf.toString('latin1', o, o + 4);
    const off = buf.readUInt32BE(o + 4);
    const comp = buf.readUInt32BE(o + 8);
    const orig = buf.readUInt32BE(o + 12);
    const raw = buf.subarray(off, off + comp);
    out[tag] = comp < orig ? inflateSync(raw) : Buffer.from(raw);
  }
  return out;
}

function cmapOf(c) {
  const n = c.readUInt16BE(2);
  let best = null;
  for (let i = 0; i < n; i++) {
    const pid = c.readUInt16BE(4 + i * 8);
    const eid = c.readUInt16BE(6 + i * 8);
    const off = c.readUInt32BE(8 + i * 8);
    const fmt = c.readUInt16BE(off);
    if ((pid === 3 && (eid === 1 || eid === 10)) || pid === 0) {
      if (!best || fmt === 12) best = { off, fmt };
    }
  }
  const map = new Map();
  if (!best) return map;
  const { off, fmt } = best;
  if (fmt === 4) {
    const segX2 = c.readUInt16BE(off + 6);
    const ends = off + 14;
    const starts = ends + segX2 + 2;
    const deltas = starts + segX2;
    const ranges = deltas + segX2;
    for (let s = 0; s < segX2 / 2; s++) {
      const end = c.readUInt16BE(ends + s * 2);
      const start = c.readUInt16BE(starts + s * 2);
      const delta = c.readInt16BE(deltas + s * 2);
      const ro = c.readUInt16BE(ranges + s * 2);
      for (let cp = start; cp <= end && cp !== 0xffff; cp++) {
        let g;
        if (ro === 0) g = (cp + delta) & 0xffff;
        else {
          g = c.readUInt16BE(ranges + s * 2 + ro + (cp - start) * 2);
          if (g !== 0) g = (g + delta) & 0xffff;
        }
        if (g) map.set(cp, g);
      }
    }
  } else if (fmt === 12) {
    const groups = c.readUInt32BE(off + 12);
    for (let i = 0; i < groups; i++) {
      const b = off + 16 + i * 12;
      const s = c.readUInt32BE(b);
      const e = c.readUInt32BE(b + 4);
      const g0 = c.readUInt32BE(b + 8);
      for (let cp = s; cp <= e; cp++) map.set(cp, g0 + (cp - s));
    }
  }
  return map;
}

// [first code point, value, value, ...] runs over consecutive code points.
function runs(entries, pick) {
  const out = [];
  let cur = null;
  let next = -1;
  for (const [cp, v] of entries) {
    if (cp !== next) {
      cur = [cp];
      out.push(cur);
    }
    cur.push(...pick(v));
    next = cp + 1;
  }
  return out;
}

const faces = {};
for (const [name, file] of Object.entries(FACES)) {
  const t = tables(readFileSync(join(ROOT, 'assets/fonts', file)));
  const upm = t.head.readUInt16BE(18);
  const longLoca = t.head.readInt16BE(50) === 1;
  const nh = t.hhea.readUInt16BE(34);
  const adv = (g) => t.hmtx.readUInt16BE(Math.min(g, nh - 1) * 4);
  const ink = (g) => {
    if (!t.glyf || !t.loca) return null;
    const at = longLoca ? t.loca.readUInt32BE(g * 4) : t.loca.readUInt16BE(g * 2) * 2;
    const to = longLoca ? t.loca.readUInt32BE(g * 4 + 4) : t.loca.readUInt16BE(g * 2 + 2) * 2;
    if (to <= at) return [0, 0];
    return [t.glyf.readInt16BE(at + 8), t.glyf.readInt16BE(at + 4)]; // yMax, yMin
  };
  const cps = [...cmapOf(t.cmap)].filter(([cp]) => cp >= 0x20 && cp <= MAX_CP).sort((a, b) => a[0] - b[0]);
  const face = { upm, adv: runs(cps, (g) => [adv(g)]) };
  if (name === 'sign800') face.ink = runs(cps, (g) => ink(g));
  faces[name] = face;
}

const body = JSON.stringify(faces).replace(/\],\[/g, '],\n[');
writeFileSync(
  join(ROOT, 'lib/ogMetrics.ts'),
  '// GENERATED by scripts/og-metrics.mjs from the WOFF files in assets/fonts.\n' +
    '// Do not edit by hand: re-run the script when a font file changes.\n' +
    '// Per face: units per em, then runs of [first code point, value...] over\n' +
    '// consecutive code points. `adv` is the advance width in font units; `ink`\n' +
    '// (signage only) is each glyph\'s [yMax, yMin] ink box in font units.\n' +
    'export interface OgFace { upm: number; adv: number[][]; ink?: number[][] }\n' +
    `export const OG_FACES: Record<'sign800' | 'sign700' | 'text600' | 'text500' | 'voice', OgFace> = ${body};\n`
);
console.log('og-metrics: wrote lib/ogMetrics.ts');
