import { NextResponse, type NextRequest } from 'next/server';

// THE CANONICAL LOWERCASE HOP LIVES HERE, NOT IN app/[slug]/page.tsx.
//
// The page can fold case on the lookup, but it cannot carry the query string
// while doing it: reading `searchParams` anywhere in that component turns the
// whole route dynamic and kills the ISR caching that generateStaticParams was
// added to win back. Measured, not guessed - with an `await searchParams` in
// the redirect branch a cold /Fort-Nite answered 500 DYNAMIC_SERVER_USAGE.
// Middleware runs before the route ever renders, so it sees the full URL,
// keeps every parameter on it, and leaves the page prerendered.
//
// What was being lost: a link a mechanic shares carries `?service=` (the
// storefront preselects that job in the request form) and `?src=` (which
// share of his the visit came from). A visitor who retyped the address with a
// capital, or a link-shortener that title-cased it, landed on a form with
// nothing selected and an attribution row that credited nobody.

// Single-segment paths that are NOT mechanic slugs. Every one of these must
// fall through untouched, because a wrong hop here does not degrade one
// storefront, it breaks the site. Compared lowercased, so /Mechanics is not
// quietly handed a second address either: whatever Next already does with a
// miscased fixed page, it keeps doing unchanged. This route exists to rescue
// a mistyped STOREFRONT link, and nothing else.
//
// Not listed because they can never reach this function: /api/*, /_next/*
// and /preview/* are excluded by the matcher below AND carry a slash, and
// the per-profile OG card is /<slug>/opengraph-image, which is two segments.
const RESERVED_PATHS = new Set([
  // Fixed marketing and legal pages.
  'mechanics',
  'customers',
  'privacy',
  'terms',
  'support',
  // The analytics dashboard (a rewrite to /stats.html) and its assets.
  'stats',
  'stats.html',
  'stats.js',
  'track.js',
  'logo.png',
  // Metadata routes generated by Next at the root.
  'robots.txt',
  'sitemap.xml',
  'favicon.ico',
  'opengraph-image',
  // Belt and braces: these are already excluded by the matcher, but a
  // one-segment request for a route group must never be rewritten either.
  'api',
  'preview',
  '_next',
]);

// A stored slug is minted lowercase and the database CHECK constraint
// mechanic_profiles_slug_format (`^[a-z0-9][a-z0-9-]{1,58}[a-z0-9]$`) means
// it can never be anything else. So anything that is not made of letters,
// digits and hyphens is not a slug with a capital in it, it is some other
// request, and percent-encoding (whose hex is uppercase by convention) is
// exactly the case that would otherwise trigger a pointless hop.
const SLUG_SHAPE = /^[A-Za-z0-9-]+$/;

export function middleware(request: NextRequest) {
  const segment = request.nextUrl.pathname.slice(1);

  // Not a single segment, already canonical, not slug-shaped, or reserved.
  if (!segment || segment.includes('/')) return NextResponse.next();
  if (!SLUG_SHAPE.test(segment)) return NextResponse.next();
  if (segment === segment.toLowerCase()) return NextResponse.next();
  if (RESERVED_PATHS.has(segment.toLowerCase())) return NextResponse.next();

  // clone() carries the query across, which is the entire point of doing this
  // here rather than in the route. One encoding detail, checked against a
  // running production build rather than assumed: a space reaches the Location
  // header as `+` even when it arrived as `%20` (Next normalises the request
  // URL before middleware ever sees it, so no amount of reading it raw changes
  // that), while a literal plus sent as `%2B` survives as `%2B`. Both forms of
  // a space decode back to a space in every parser that reads these - the
  // storefront's `?service=` preselect and track.js's `?src=` alike - so the
  // meaning of the link is preserved, which is what was lost before.
  //
  // 307 and never 308, for the same reason the retired-slug hop in
  // app/[slug]/page.tsx uses redirect() and not permanentRedirect(): a
  // permanent redirect is cached by the browser, and a rename A -> B -> A
  // would then loop forever on a hop nobody can clear.
  const canonical = request.nextUrl.clone();
  canonical.pathname = `/${segment.toLowerCase()}`;
  return NextResponse.redirect(canonical, 307);
}

export const config = {
  // One path segment only, and never the API, the build output or a private
  // preview token. The in-function guards above are the authority on what
  // gets redirected; this exists so the function is not invoked for the
  // thousands of asset requests it would decline anyway.
  matcher: ['/((?!api/|_next/|preview/)[^/]+)'],
};
